### ISSUE TITLE
Missing designs

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#328]
Let's use this issue to round up all the missing designs lists.

## designed
- [x] Pre-boosted proposal (card & page) tweaks (e.g. bottom threshold) - https://zpl.io/beDJGEq
- [x] History page - indicate why a proposal has passed or failed - https://zpl.io/agPqJyA
- [x] Tooltips throughout the app, like hover over rewards to see amount vs. % - https://zpl.io/beDJGEq
- [x] What do we show when someone doesn't have a name? Address? - yes
- [x] For multiple rewards while creating a proposal, the current design doesn't seem to work... What should multiple rewards actually look like for now? - https://zpl.io/beoMrdY
- [x] There is currently a user dropdown which shows basic information to each user. Do we want to keep that?
- [x] Currently, buy GEN has a submenu with markets - what should the new submenu look like - https://zpl.io/adp3Wg7

## issue created
- [x] Loading animation / definition - #481
- [x] Once over on homepage to bring it in line with new look and feel - #482
- [x] Tour intro - #393 
- [x] New design for notifications - #480

**Comment by tibetsprague** [comment]
Do we want an execute button on the history page for expired proposals that haven't yet been executed?

**Comment by A-Zak** [comment]
@brodeur I've updated this with your list... if you find anything new, just added it here ^_^

**Comment by brodeur** [comment]
- [ ]  Notifications have been broken for a bit, but they also should be accounted for. Notifies users about status of MM transactions

**Comment by jellegerbrandy** [comment]
@A-Zak  any progress here?
