### ISSUE TITLE
The Great Alchemy Consolidation Issue

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#858]
# Refactoring

## URL schemes

| Currently    | Let's change it to              |
|--------------|--------------|
|`/dao/${daoADdresss}/proposals/${schemeId}` |/dao/${daoADdresss}/scheme/${schemeId}

- [x] this is done in #920 

## Global state handling

- [x]  clean up the redux state (e.g. remove dead (unused parts, like `arc` and `ui`, from the state, remove dead functions in `reducers`  and `selectors`, etc)

- [x] [perhaps...] consider not using redux at all, but the (easier, lighter) https://reactjs.org/docs/context.html

## Clean up comments

* [x] remove all "remind me of stuff" code and create issues. working on this in #924

## Dead code

- [x] remove code  that is obviously dead (like `operations.ts`)
- [ ] Use some test coverage tool to see which code is (and is not) covered by our tests
- [x] #450 (mintgen script)

## Linting

- [x] Ticket is [here](https://github.com/daostack/alchemy/issues/915).  We are still working with a large set of disabled rules in `tslint.json`. Some useful ones that should really be activated are `no-console`, `no-var-requires`, `no-shadowed-variable`. Others that are just plain common sense are `max-line-length`, `no-unused-expression`, 

## Dependencies

- [x] Review app depdencies and see what we can do without (#313)
- [x] upgrade dependencies where possible #917
- [ ] try to avoid having including different versions of the same package

## DutchX-specific code

-  [x] should be removed (apart from the DuthX.json file, from whcih all should be generated). This specifically concerns the `ProposalSummaryDutchX.ts` file, which shoudl disappear.

## Directory structure

| Currently    | Let's change it to              |
|--------------|--------------|
| /DaoList/ | Daos
| /CreateProposal/ | /Proposal/Create/
| /ViewDao/ | /Dao
| /Proposal/Predictions | /Proposal/Staking
| - | `Scheme/` a new directory for the scheme stuff (like the `SchemeProposalsContainer`)

## Component naming

We use `View` and `Container` suffixes more or less at random, let's just drop those:

| Currently    | Let's change it to              |
|--------------|--------------|
|  ReputationView | Reputation
| ViewDao | Dao
| DaoHistoryContainer | History
| DaoRedemptionsContainer | Redemptions
| DaoMembersContainer | Members
| SchemeProposalsContainer |  Scheme | 
| AllSchemesContainer | DAOHome |

## Modals

- [ ] We should use one single system, not have different logic for each component. We now have (afaics)

* We use `react-router-modal`  for proposal creation, which manages open/closing modals on the basis of URLs
* we have the `PreTransactionModal`  which is a kind of generic container for Modal dialogs (we use this for stakign and redeeming and voting, I think), but does not use the modal state handling of react-router-modal (but instead passes "close" methods in the props)
* We have  the `VotersModal` that just does its own thing
* Perhaps others. (We used to have yet another modal handlign system for the tour)

this is bad not only because of the code duplication or the nasty pass-a-callback-to-close-the-modal pattern, but also because we have modal CSS spread out in different place.s

1. Choose ONE implementation pattern based on some standard react package (react-router-modal is okayish) and use the method is provides for opening/closing modals
2. Collect all modals in a single `/Modals` directory, so they can easily share styles and components

## Small refactoring things

- [x] utils.ts  does not need its a class within the file... [fixed in #875]
- [x] do not commit the genersted scss.d.ts files #838 

## Meta

- [ ] Clean up our issues list
- [x] Reconsider github description of the project
- [x] clean up package.json
- [x] delete unused branches

# Testing

Cf. issues #766, #750, #760, #629 , #361 

# Critical issues

https://github.com/daostack/alchemy/labels/critical

**Comment by leviadam** [comment]
Great work @jellegerbrandy 
I want to echo here the need in a much stronger linter.

**Comment by tibetsprague** [comment]
/dao/${daoAddress}/profile/${account} doesnt really make sense because you can access the profile from anywhere. we use the dao query parameter when you acccess it from a DAO to show the reputation and tokens within that DAO if the profile is accessed from within a DAO. we could just remove that functionality, but why not keep it?

**Comment by tibetsprague** [comment]
i think the create proposal page/modal needs to be its own URL so we can link to it and pass that link around. whether its a modal or not doesnt really matter, having a URL is more important to me. and having it be a modal with a URL doesnt seem that weird to me honestly

**Comment by tibetsprague** [comment]
the use of Container for components is a common usage when indicating which components are connected to redux. since we are barely using Redux anymore they dont make much sense. I do think it would be nice to have a naming convention that indicates which components are "pages" or "views", vs sub components

**Comment by tibetsprague** [comment]
i dont' really understand your issue with the modals... they all use React Router Modal. having to pass in the close function is a little weird, but i'm not sure there's a better way in React. ironically if you don't want to do that then each modal will need to have its own URL, which contradicts your other idea above :) I'm happy to explore some refactoring of the modals, but i doubt there's some major significant better way to do it. we could also look into other libraries...

**Comment by jellegerbrandy** [comment]
About the modals: many of them, indeed, inherit from react-router-modal, but as I understand it only the new proposal modal is actually USING `react-router-modal` as intended. 

So here is a proposal:

- use `react-router-modal` for all modals. (Meaning: use the route to open and close them, i.e. liek in new proposal, instead of doing the callback stuff). That means giving each modal its own URL.
- move all the modal sinto their own directory `/Modals`, where they can easily share styles. (This makes sense bc modals interrupt the flow of the app, and can, in theory, be inserted anywhere, so they do not really belong to any component of part of the page)
- (then refactor a bit and actually re-use the styles and code)

**Comment by jellegerbrandy** [comment]
About URLs: so what I am aiming for here is consistency. 

* use a separate url for all modals, or for none, but not for only one of them
* use query parameters or do not use them, but do not use them only for one single page

**Comment by jellegerbrandy** [comment]
Specifically, about the profile page, you make a good point about te profile page being accessible also without the DAO, but that point has nothing to do with the choice of using the query part of the URL of the path part of the URL.

Typically, query parameters are used for querying (sorting, filtering, paging), but you can put any information anywhere you wantin the URL. 

So for the profile, I'd still propose to not use the query string, but instead do something like: 
So, wrt to the profile page to me it makes more sense to have a scheme like: 

`profile/0x12455` <- your "generic" profile page
`dao/0x124455/profile/0x132445` <- your profile page in the DAO **OR**
`profile/0x132445/dao/012344` <- your profile page in the DAO

anyway, this is probably the least important point in the whole issue :-)

**Comment by tibetsprague** [comment]
lets hash this out in a meeting :)

one other thing id like to do is have consistency for how we handle the <Subscribe> components, if we are going to separate into two components then can we have the <Subscribe> one at the top of the file? and consistently name them and the various Props interfaces too

**Comment by jellegerbrandy** [comment]
consistency sounds good. Can you describe what it that means concretely,
and add it to the description of the issue?

**Comment by leviadam** [comment]
Cleaned all the unused branches.

**Comment by tibetsprague** [comment]
I think DaoHistoryContainer should become DaoHistoryPage, we still want the Dao part because we could have a user history in the future, and I think its useful to say "page" to indicate which components are distinct pages with distinct URLs

**Comment by leviadam** [comment]
@jellegerbrandy 
I looked for test coverage tools. Only found [this](https://www.npmjs.com/package/wdio-test-coverage-reporter), which looks dead, and did not work when I tried it.

**Comment by jellegerbrandy** [comment]
Ok, closing this as the sprint is over. Many thanks all :-)
